import { eq, and, desc } from 'drizzle-orm'
import { db } from '@database/client'
import { 
  invoices, 
  invoiceItems 
} from '@database/schemas/invoices.schema'
import type { 
  CreateInvoiceInput, 
  InvoiceWithRelations 
} from '../types/invoice.types'
import { calculateInvoiceTotals } from '../utils/invoice-calculations'

/**
 * Get all invoices for a user
 */
export async function getInvoices(userId: string): Promise<InvoiceWithRelations[]> {
  return db.query.invoices.findMany({
    where: eq(invoices.userId, userId),
    orderBy: desc(invoices.createdAt),
    with: {
      client: true,
      items: true
    }
  })
}

/**
 * Get a single invoice by ID
 */
export async function getInvoiceById(
  id: string, 
  userId: string
): Promise<InvoiceWithRelations | undefined> {
  return db.query.invoices.findFirst({
    where: and(
      eq(invoices.id, id),
      eq(invoices.userId, userId)
    ),
    with: {
      client: true,
      items: true
    }
  })
}

/**
 * Create a new invoice (draft)
 */
export async function createInvoice(
  userId: string,
  data: CreateInvoiceInput
) {
  // Calculate totals
  const { subtotal, iva, total } = calculateInvoiceTotals(data.items)
  
  // Transaction: Insert invoice + items
  const result = await db.transaction(async (tx) => {
    // 1. Insert invoice
    const [invoice] = await tx
      .insert(invoices)
      .values({
        userId,
        clientId: data.clientId,
        serie: data.serie || null,
        formaPago: data.formaPago,
        metodoPago: data.metodoPago,
        usoCfdi: data.usoCfdi,
        moneda: data.moneda || 'MXN',
        subtotal: subtotal.toString(),
        iva: iva.toString(),
        retenciones: '0',
        total: total.toString(),
        estatus: 'draft',
        folio: 0 // Will be auto-generated by DB trigger
      })
      .returning()
    
    // 2. Insert items
    const itemsToInsert = data.items.map(item => ({
      invoiceId: invoice.id,
      claveProdServ: item.claveProdServ || '84111506',
      descripcion: item.descripcion,
      cantidad: item.cantidad.toString(),
      unidad: item.unidad || 'E48',
      valorUnitario: item.valorUnitario.toString(),
      importe: (item.cantidad * item.valorUnitario).toString()
    }))
    
    await tx.insert(invoiceItems).values(itemsToInsert)
    
    return invoice
  })
  
  return result
}

/**
 * Update invoice
 */
export async function updateInvoice(
  id: string,
  userId: string,
  data: Partial<CreateInvoiceInput>
) {
  // Verify ownership
  const invoice = await getInvoiceById(id, userId)
  if (!invoice) {
    throw new Error('Invoice not found')
  }
  
  if (invoice.estatus !== 'draft') {
    throw new Error('Cannot edit a timbrada or cancelled invoice')
  }
  
  // Update logic here
  // TODO: Implement update with items
  
  return invoice
}

/**
 * Delete invoice (only drafts)
 */
export async function deleteInvoice(id: string, userId: string) {
  const invoice = await getInvoiceById(id, userId)
  
  if (!invoice) {
    throw new Error('Invoice not found')
  }
  
  if (invoice.estatus !== 'draft') {
    throw new Error('Cannot delete a timbrada or cancelled invoice')
  }
  
  await db.delete(invoices).where(eq(invoices.id, id))
  
  return { success: true }
}
