import { eq, and, desc } from 'drizzle-orm'
import { db } from '@database/client'
import {
  invoices,
  invoiceItems
} from '@database/schemas/invoices.schema'
import type {
  CreateInvoiceInput,
  InvoiceWithRelations
} from '../types/invoice.types'
import { calculateInvoiceTotals } from '../utils/invoice-calculations'

/**
 * Get all invoices for a user
 */
export async function getInvoices(userId: string): Promise<InvoiceWithRelations[]> {
  return db.query.invoices.findMany({
    where: eq(invoices.userId, userId),
    orderBy: desc(invoices.createdAt),
    with: {
      client: true,
      items: true
    }
  })
}

/**
 * Get a single invoice by ID
 */
export async function getInvoiceById(
  id: string,
  userId: string
): Promise<InvoiceWithRelations | undefined> {
  return db.query.invoices.findFirst({
    where: and(
      eq(invoices.id, id),
      eq(invoices.userId, userId)
    ),
    with: {
      client: true,
      items: true
    }
  })
}

/**
 * Create a new invoice (draft)
 */
export async function createInvoice(
  userId: string,
  data: CreateInvoiceInput
) {
  // Calculate totals
  const { subtotal, iva, total } = calculateInvoiceTotals(data.items)

  // Transaction: Insert invoice + items
  const result = await db.transaction(async (tx) => {
    // 1. Insert invoice
    const [invoice] = await tx
      .insert(invoices)
      .values({
        userId,
        clientId: data.clientId,
        serie: data.serie || null,
        paymentForm: data.paymentForm,
        paymentMethod: data.paymentMethod,
        cfdiUsage: data.cfdiUsage,
        currency: data.currency || 'MXN',
        subtotal: subtotal.toString(),
        iva: iva.toString(),
        withholdings: '0',
        total: total.toString(),
        status: 'draft',
        folio: 0 // Will be auto-generated by DB trigger
      })
      .returning()

    // 2. Insert items
    const itemsToInsert = data.items.map(item => ({
      invoiceId: invoice.id,
      productServiceCode: item.productServiceCode || '84111506',
      description: item.description,
      quantity: item.quantity.toString(),
      unit: item.unit || 'E48',
      unitPrice: item.unitPrice.toString(),
      amount: (item.quantity * item.unitPrice).toString()
    }))

    await tx.insert(invoiceItems).values(itemsToInsert)

    return invoice
  })

  return result
}

/**
 * Update invoice (only drafts)
 */
export async function updateInvoice(
  id: string,
  userId: string,
  data: CreateInvoiceInput
) {
  const existing = await getInvoiceById(id, userId)
  if (!existing) {
    throw new Error('Factura no encontrada')
  }

  if (existing.status !== 'draft') {
    throw new Error('Solo se pueden editar borradores')
  }

  const { subtotal, iva, total } = calculateInvoiceTotals(data.items)

  const result = await db.transaction(async (tx) => {
    const [updated] = await tx
      .update(invoices)
      .set({
        clientId: data.clientId,
        serie: data.serie || null,
        paymentForm: data.paymentForm,
        paymentMethod: data.paymentMethod,
        cfdiUsage: data.cfdiUsage,
        currency: data.currency || 'MXN',
        subtotal: subtotal.toString(),
        iva: iva.toString(),
        total: total.toString(),
      })
      .where(and(eq(invoices.id, id), eq(invoices.userId, userId)))
      .returning()

    // Replace items: delete old, insert new
    await tx.delete(invoiceItems).where(eq(invoiceItems.invoiceId, id))

    const itemsToInsert = data.items.map(item => ({
      invoiceId: id,
      productServiceCode: item.productServiceCode || '84111506',
      description: item.description,
      quantity: item.quantity.toString(),
      unit: item.unit || 'E48',
      unitPrice: item.unitPrice.toString(),
      amount: (item.quantity * item.unitPrice).toString()
    }))

    await tx.insert(invoiceItems).values(itemsToInsert)

    return updated
  })

  return result
}

/**
 * Delete invoice (only drafts)
 */
export async function deleteInvoice(id: string, userId: string) {
  const invoice = await getInvoiceById(id, userId)

  if (!invoice) {
    throw new Error('Invoice not found')
  }

  if (invoice.status !== 'draft') {
    throw new Error('Cannot delete a timbrada or cancelled invoice')
  }

  await db.delete(invoices).where(eq(invoices.id, id))

  return { success: true }
}
