import { eq, and, desc } from 'drizzle-orm'
import { db } from '@database/client'
import {
  invoices,
  invoiceItems
} from '@database/schemas/invoices.schema'
import type {
  CreateInvoiceInput,
  InvoiceWithRelations
} from '../types/invoice.types'
import { calculateInvoiceTotals } from '../utils/invoice-calculations'
import { getIssuingProfileById } from '@features/fiscal-profile/services/fiscal-profile.service'
import { profileHasCSD, isCertExpired } from '@features/fiscal-profile/types/fiscal-profile.types'
import { decryptString } from '@features/fiscal-profile/services/certificate.service'
import { buildCfdiXml } from '@features/stamping/services/cfdi-xml-builder.service'
import { sealXml } from '@features/stamping/services/xml-seal.service'
import { stampInvoice as swStampInvoice, cancelInvoice as swCancelInvoice } from '@features/stamping/services/sw-client.service'
import type { StampingResult, CancellationResult } from '@features/stamping/types/stamping.types'
import { uploadFile } from '@features/storage/services/r2.service'
import { generateInvoicePdf } from '@features/storage/services/pdf-generator.service'

/**
 * Get all invoices for a user
 */
export async function getInvoices(userId: string): Promise<InvoiceWithRelations[]> {
  return db.query.invoices.findMany({
    where: eq(invoices.userId, userId),
    orderBy: desc(invoices.createdAt),
    with: {
      client: true,
      items: true
    }
  })
}

/**
 * Get a single invoice by ID
 */
export async function getInvoiceById(
  id: string,
  userId: string
): Promise<InvoiceWithRelations | undefined> {
  return db.query.invoices.findFirst({
    where: and(
      eq(invoices.id, id),
      eq(invoices.userId, userId)
    ),
    with: {
      client: true,
      items: true
    }
  })
}

/**
 * Create a new invoice (draft)
 */
export async function createInvoice(
  userId: string,
  data: CreateInvoiceInput
) {
  // Calculate totals
  const { subtotal, iva, total } = calculateInvoiceTotals(data.items)

  // Transaction: Insert invoice + items
  const result = await db.transaction(async (tx) => {
    // 1. Insert invoice
    const [invoice] = await tx
      .insert(invoices)
      .values({
        userId,
        clientId: data.clientId,
        issuingProfileId: data.issuingProfileId || null,
        serie: data.serie || null,
        paymentForm: data.paymentForm,
        paymentMethod: data.paymentMethod,
        cfdiUsage: data.cfdiUsage,
        currency: data.currency || 'MXN',
        subtotal: subtotal.toString(),
        iva: iva.toString(),
        withholdings: '0',
        total: total.toString(),
        status: 'draft',
        folio: 0 // Will be auto-generated by DB trigger
      })
      .returning()

    // 2. Insert items
    const itemsToInsert = data.items.map(item => ({
      invoiceId: invoice.id,
      productServiceCode: item.productServiceCode || '84111506',
      description: item.description,
      quantity: item.quantity.toString(),
      unit: item.unit || 'E48',
      unitPrice: item.unitPrice.toString(),
      amount: (item.quantity * item.unitPrice).toString()
    }))

    await tx.insert(invoiceItems).values(itemsToInsert)

    return invoice
  })

  return result
}

/**
 * Update invoice (only drafts)
 */
export async function updateInvoice(
  id: string,
  userId: string,
  data: CreateInvoiceInput
) {
  const existing = await getInvoiceById(id, userId)
  if (!existing) {
    throw new Error('Factura no encontrada')
  }

  if (existing.status !== 'draft') {
    throw new Error('Solo se pueden editar borradores')
  }

  const { subtotal, iva, total } = calculateInvoiceTotals(data.items)

  const result = await db.transaction(async (tx) => {
    const [updated] = await tx
      .update(invoices)
      .set({
        clientId: data.clientId,
        issuingProfileId: data.issuingProfileId || null,
        serie: data.serie || null,
        paymentForm: data.paymentForm,
        paymentMethod: data.paymentMethod,
        cfdiUsage: data.cfdiUsage,
        currency: data.currency || 'MXN',
        subtotal: subtotal.toString(),
        iva: iva.toString(),
        total: total.toString(),
      })
      .where(and(eq(invoices.id, id), eq(invoices.userId, userId)))
      .returning()

    // Replace items: delete old, insert new
    await tx.delete(invoiceItems).where(eq(invoiceItems.invoiceId, id))

    const itemsToInsert = data.items.map(item => ({
      invoiceId: id,
      productServiceCode: item.productServiceCode || '84111506',
      description: item.description,
      quantity: item.quantity.toString(),
      unit: item.unit || 'E48',
      unitPrice: item.unitPrice.toString(),
      amount: (item.quantity * item.unitPrice).toString()
    }))

    await tx.insert(invoiceItems).values(itemsToInsert)

    return updated
  })

  return result
}

/**
 * Delete invoice (only drafts)
 */
export async function deleteInvoice(id: string, userId: string) {
  const invoice = await getInvoiceById(id, userId)

  if (!invoice) {
    throw new Error('Invoice not found')
  }

  if (invoice.status !== 'draft') {
    throw new Error('Cannot delete a timbrada or cancelled invoice')
  }

  await db.delete(invoices).where(eq(invoices.id, id))

  return { success: true }
}

/**
 * Stamp an invoice via SW Sapien PAC (pre-sealed XML)
 */
export async function stampInvoice(
  invoiceId: string,
  userId: string,
): Promise<StampingResult> {
  const invoice = await getInvoiceById(invoiceId, userId)
  if (!invoice) throw new Error('Factura no encontrada')
  if (invoice.status !== 'draft') throw new Error('Solo se pueden timbrar borradores')
  if (!invoice.issuingProfileId) throw new Error('La factura no tiene un perfil emisor asignado')

  const profile = await getIssuingProfileById(invoice.issuingProfileId, userId)
  if (!profile) throw new Error('Perfil emisor no encontrado')
  if (!profileHasCSD(profile)) throw new Error('El perfil emisor no tiene certificados CSD configurados')
  if (isCertExpired(profile)) throw new Error('El certificado CSD ha expirado')

  const keyPassword = decryptString(profile.keyPassword!)

  // Build unsigned XML
  const unsignedXml = buildCfdiXml({
    invoice,
    profile,
    certificateBase64: profile.cerBase64!,
    certificateNumber: profile.certSerialNumber!,
  })

  // Seal: generate cadena original, sign, and set Sello attribute
  const sealedXml = sealXml({
    xml: unsignedXml,
    cerBase64: profile.cerBase64!,
    keyBase64: profile.keyBase64!,
    keyPassword,
  })

  const result = await swStampInvoice(sealedXml)

  if (!result.success) {
    return result
  }

  // Save stamping result to DB first
  await db
    .update(invoices)
    .set({
      status: 'timbrada',
      uuid: result.uuid,
      xmlContent: result.cfdi,
      satCertificateNumber: result.satCertificateNumber,
      cfdiSignature: result.cfdiSignature,
      satSignature: result.satSignature,
      satOriginalChain: result.satOriginalChain,
      qrCode: result.qrCode,
      stampedAt: result.stampedAt ? new Date(result.stampedAt) : new Date(),
    })
    .where(eq(invoices.id, invoiceId))

  // Upload XML + PDF to R2 (non-blocking — invoice is already timbrada)
  try {
    const stampedInvoice = await getInvoiceById(invoiceId, userId)
    if (stampedInvoice && result.uuid && result.cfdi) {
      const xmlBuffer = Buffer.from(result.cfdi, 'utf-8')
      const pdfBuffer = await generateInvoicePdf(stampedInvoice, userId)

      const [xmlKey, pdfKey] = await Promise.all([
        uploadFile(userId, result.uuid, xmlBuffer, 'xml'),
        uploadFile(userId, result.uuid, pdfBuffer, 'pdf'),
      ])

      await db
        .update(invoices)
        .set({ xmlUrl: xmlKey, pdfUrl: pdfKey })
        .where(eq(invoices.id, invoiceId))
    }
  } catch (error) {
    // R2 upload failure should not break the stamping flow
    console.error('R2 upload failed (invoice is still timbrada):', error)
  }

  return result
}

/**
 * Cancel a stamped invoice via SW Sapien PAC
 */
export async function cancelInvoice(
  invoiceId: string,
  userId: string,
  reason: '01' | '02' | '03' | '04',
  replacementUuid?: string,
): Promise<CancellationResult> {
  const invoice = await getInvoiceById(invoiceId, userId)
  if (!invoice) throw new Error('Factura no encontrada')
  if (invoice.status !== 'timbrada') throw new Error('Solo se pueden cancelar facturas timbradas')
  if (!invoice.uuid) throw new Error('La factura no tiene UUID fiscal')
  if (!invoice.issuingProfileId) throw new Error('La factura no tiene perfil emisor')

  const profile = await getIssuingProfileById(invoice.issuingProfileId, userId)
  if (!profile) throw new Error('Perfil emisor no encontrado')
  if (!profileHasCSD(profile)) throw new Error('El perfil emisor no tiene certificados CSD configurados')

  const keyPassword = decryptString(profile.keyPassword!)

  const result = await swCancelInvoice({
    uuid: invoice.uuid,
    issuerRfc: profile.rfc,
    reason,
    replacementUuid,
    cerBase64: profile.cerBase64!,
    keyBase64: profile.keyBase64!,
    keyPassword,
  })

  if (!result.success) {
    return result
  }

  await db
    .update(invoices)
    .set({
      status: 'cancelada',
      cancellationReason: reason,
      cancelledAt: new Date(),
    })
    .where(eq(invoices.id, invoiceId))

  return result
}
